### ISSUE TITLE
Error on opening pouch

### ISSUE THREAD

**Issue by Korinocho** [LMBishop/MoneyPouch#1]
When im trying to open some pouch of money it gives me this error:

[18:02:35 ERROR]: Could not pass event PlayerInteractEvent to MoneyPouch v3.1
java.lang.IllegalArgumentException: bound must be greater than origin
        at java.util.concurrent.ThreadLocalRandom.nextLong(Unknown Source) ~[?:1.8.0_241]
        at com.leonardobishop.moneypouch.events.UseEvent.usePouch(UseEvent.java:63) ~[?:?]
        at com.leonardobishop.moneypouch.events.UseEvent.onPlayerUse(UseEvent.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-334]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:456) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1413) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

Using Paper 1.15.2 (Compilation 334)

**Comment by LMBishop** [comment]
One of your pouches has an incorrect range. Make sure the max is not greater than the min.

**Comment by Korinocho** [comment]
tier:
    1:
      name: '&e&lTier I &f| Money Pouch'
      item: 'ENDER_CHEST'
      pricerange:
        from: '1000'
        to: '10000'
      lore:
        - '&7This pouch of loot was stolen'
        - '&7from the kings castle by a very'
        - '&7strange person...'
    2:
      name: '&e&lTier II &f| Money Pouch'
      item: 'ENDER_CHEST'
      pricerange:
        from: '10001'
        to: '50000'
      lore:
        - '&7This mysterious object was dug'
        - '&7out the grass by some very brave'
        - '&7players. It holds great power &'
        - '&7loot.'
    3:
      name: '&e&lTier III &f| Money Pouch'
      item: 'ENDER_CHEST'
      pricerange:
        from: '50001'
        to: '150000'
      lore:
        - '&7This shining object was taken'
        - '&7from the cave of the great legend'
        - '&7known as Herobrine. It wields massive'
        - '&7power.'
    4:
      name: '&e&lTier IV &f| Money Pouch'
      item: 'ENDER_CHEST'
      pricerange:
        from: '150001'
        to: '300000'
      lore:
        - '&7This heavy chest was dropped by'
        - '&7the great Ender Dragon. Only four'
        - '&7brave men could beat the Ender Dragon'
    5:
      name: '&e&lTier V &f| Money Pouch'
      item: 'ENDER_CHEST'
      pricerange:
        from: '300001'
        to: '500000'
      lore:
        - '&7This great chest was stolen'
        - '&7from the Wither boss. For some'
        - '&7odd reason there is no nether star'

Isnt this right?
